version: "3"
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
  authentication:
    build: ./authentication-service
    image: rcmendes/authentication-service:latest
    ports: 
      - "9001:9001"
  reverse:
    build: ./reverse-text
    image: rcmendes/reverse-text-service:latest
    ports: 
      - "9000:9000"
  echo:
    build: 
      context: ./echo
      dockerfile: src/main/docker/Dockerfile.jvm
    image: rcmendes/echo-service:latest
    ports: 
      - "8080:8080"
